### ISSUE TITLE
PHP Undefined Variable Warning

### ISSUE THREAD

**Issue by Jontyy** [virtuozzo/OnApp-PHP-Wrapper-External#1]
Hi,

Getting PHP warnings when working with CDNResource.php `Notice:  Undefined variable: actions` on line 262. 

https://github.com/OnApp/OnApp-PHP-Wrapper-External/blob/master/CDNResource.php#L262

**Comment by yuriy-yakubskiy** [comment]
Fixed!

https://github.com/OnApp/OnApp-PHP-Wrapper-External/commit/c79ff5b198ff90a4f2c6385ff9300782fb24b52d

Thanks!
- -
  Yuriy Yakubskiy

**Comment by Jontyy** [comment]
Hi @yuriy-yakubskiy , thanks for that.

By the way, I develop with strict mode enabled so I've noticed a few warnings here and there, would you like me to post them as issues here or are you open to pull requests?

John.

**Comment by yuriy-yakubskiy** [comment]
John,
Yes, sure! We welcome feedback and _contributions_ of *any kind. *
*
*
- -
  Best Regards,
  Yuriy Yakubskiy

17 ÁÐÒÅÌÑ 2012 Ç. 16:25 ÐÏÌØÚÏ×ÁÔÅÌØ John White <
reply@reply.github.com
