### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ghost** [virtuozzo/OnApp-PHP-Wrapper-External#14]
Currently there is no defined license for this repository.  Perhaps adding this in a LICENSE file would be a good idea?

```
Copyright © 2013 by OnApp

This library is free software; you can redistribute it and/or modify
it under the same terms as PHP itself, either PHP version 5.3 or,
at your option, any later version of PHP 5 you may have available.
```

(Shamelessly stolen from [Here](https://raw.github.com/OnApp/OnApp-Perl-Wrapper/master/README))

As per this [comment by Caroline](https://onappdev.atlassian.net/wiki/display/onappdownloads/PHP+Wrapper?focusedCommentId=32210958#comment-32210958) this may not be the correct license, but I believe they were confused to the question being asked.

Regardless, a license defined in the repository would be fantastic.

**Comment by prado1991** [comment]
added from version 5.4
