### ISSUE TITLE
No recipes support

### ISSUE THREAD

**Issue by zba** [virtuozzo/OnApp-PHP-Wrapper-External#19]
No recipes support in API wrapper, I made one myself, but not sure that it could be pulled to your one.

**Comment by ghost** [comment]
Hey,

Send us pull request or link to repo/commit and we'll see how to include it into wrapper.

**Comment by zba** [comment]
Hi, It is working fine, but i writen it to be compatible with upstream without need to readd new versions every time, btw, what I really not like with  current implementation, that on every onapp upgrade my backend brokes, because of this 

case: 3.2, etc things, 

In my part of code in Recipes.php I tried to implement possible solution for this.

**Comment by zba** [comment]
also please check https://github.com/OnApp/OnApp-PHP-Wrapper-External/pull/16 it fixes serious problem with IP implementation.

**Comment by luceos** [comment]
I started work on implementation due to the need for running recipes on vm's. A pull request will follow once we have our implementation working without issues in development:

https://github.com/OnApp/OnApp-PHP-Wrapper-External/compare/3.5.0...Luceos:3.5.0?expand=1

**Comment by luceos** [comment]
There is one issue; the http code once a recipe has been scheduled is 207; the OnApp class (line 959+) does not see this as a valid response.

**Comment by zba** [comment]
@prado1991 Any comment on closing not implemented features ?
