### ISSUE TITLE
Add possibility to define a connection and overall timeout

### ISSUE THREAD

**Issue by dol** [virtuozzo/OnApp-PHP-Wrapper-External#2]
The current implementation has a infinite connection timeout.

A global setting of the timeout would be nice.

---

 curl_setopt( $this->_ch, CURLOPT_TIMEOUT, $this->options[ ONAPP_OPTION_CURL_TIMEOUT ] );
 curl_setopt( $this->_ch, CURLOPT_CONNECTTIMEOUT, $this->options[ ONAPP_OPTION_CURL_CONNECTTIMEOUT ]); 

---

See http://www.quora.com/PHP/Whats-the-difference-between-CURLOPT_CONNECTTIMEOUT-and-CURLOPT_TIMEOUT for more informations.

**Comment by OnApp** [comment]
Will be implemented in new wrapper version.
