### ISSUE TITLE
Composer support?

### ISSUE THREAD

**Issue by rendragnet** [virtuozzo/OnApp-PHP-Wrapper-External#28]
Hi Team,

Could you please add a composer.json, so we can pull this into our project by simply adding it to composer? :)

Thanks,

Damien

**Comment by dol** [comment]
We use it internally with:

```
{
    "name": "onapp/onapp",
    "type": "library",
    "keywords": [],
    "description": "onApp client library",
    "require":{
        "ext-mbstring": "*"
    },
    "autoload": {
        "files" : ["OnAppInit.php"]
    },
    "license": "unknown"
}
```

**Comment by ghost** [comment]
We'll add it in next release.
@dol thanks.

**Comment by dol** [comment]
In addition, you need to publish (submit) your package on https://packagist.org/ .

**Comment by ghost** [comment]
I know. It's not a problem.
Thanks.

**Comment by dol** [comment]
:cool:

**Comment by luceos** [comment]
Finally; let me know when to take down my composer version of the library: https://packagist.org/packages/luceos/on-app

**Comment by luceos** [comment]
No composer support in 4.0.0. I will update my package again. Or should I send in a pull request for a composer version @Lev-Bartashevsky ?

**Comment by callmehuyv** [comment]
Please support composer.

**Comment by prado1991** [comment]
OnApp php wrapper has composer support from version 5.4 - https://packagist.org/packages/onapp/onapp-php-wrapper-external
