### ISSUE TITLE
Redirect url

### ISSUE THREAD

**Issue by karborator** [virtuozzo/OnApp-PHP-Wrapper-External#36]
Hi , 

I saw that when we create instance of OnApp_Factory , 
there is "redirect_url" param at response info array , but it is empty string. 

( response['info']['redirect_url'] )

So, what is the way to fetch the redirect url ? 

What I'm looking for is to create user session like cPannel , where after that I can redirect the user.

**Comment by prado1991** [comment]
The wrapper doesn't generate "redirect_url" param. 
curl_getinfo() function returns this param.
