### ISSUE TITLE
Missung ONAPP_FIELD_CLASS for multiple fields

### ISSUE THREAD

**Issue by dol** [virtuozzo/OnApp-PHP-Wrapper-External#37]
Some 'array' fields have a missing `ONAPP_FIELD_CLASS` field declaration. E.g: https://github.com/OnApp/OnApp-PHP-Wrapper-External/blob/1fcce7da33ed751eb540cae190847d38156d913b/VirtualMachine.php#L621

This will lead to the following problem:
The JSON caster at https://github.com/OnApp/OnApp-PHP-Wrapper-External/blob/1fcce7da33ed751eb540cae190847d38156d913b/Helper/Caster/JSON.php#L143 will set the `DataHolder::className` to `null`.
This leads to initializing a `OnApp_` class which not exists in https://github.com/OnApp/OnApp-PHP-Wrapper-External/blob/1fcce7da33ed751eb540cae190847d38156d913b/Helper/Caster.php#L70.

**Comment by prado1991** [comment]
it will not initialize OnApp_ class which not exists, it will output something like this:

[_preferred_hvs] => DataHolder Object
                (
                    [APIVersion] => 5.4
                    [className] => 
                    [data] => Array
                        ....
