### ISSUE TITLE
getList: argument _target_join_id not set

### ISSUE THREAD

**Issue by drwmrrs** [virtuozzo/OnApp-PHP-Wrapper-External#4]
Hi Guys,

I'm getting the following error when using the WHMCS module, more specifically, when in Products / Services > Edit
`
Fatal error: FILE => '/home/user/public_html/includes/wrapper/HypervisorZone/NetworkJoin.php', LINE => '176' getList: argument _target_join_id not set. in /home/home/public_html/includes/wrapper/Helper/Logger.php on line 148
`

Any ideas?

**Comment by yatskovets** [comment]
Hello,

You need to use branch 3.0.0 where this problem was fixed.

Thanks,
Andrew

**Comment by drwmrrs** [comment]
Hi Andrew,

Thanks for your reply; this has fixed the issue.
