### ISSUE TITLE
Undefined index: class in JSON.php (line 144)

### ISSUE THREAD

**Issue by developmatt** [virtuozzo/OnApp-PHP-Wrapper-External#40]
I get this Exception when I try to get the Virtual Machine billing statistics. 

This happens in `$tmp->className  = $this->map[ $name ][ ONAPP_FIELD_CLASS ];` where ONAPP_FIELD_CLASS  have the 'class' value and there is no field 'class' in $this->map[ $name ]

**Comment by bohze** [comment]
We can not reproduce this issue. 
Can you check what you get from http://onappIP/virtual_machines/1001/vm_stats.json request in browser, and by this code:
(replace 1001 with your virtual_machines_id)
<pre>
require_once 'onapp-php-wrapper/OnAppInit.php';
$onapp = new OnApp_Factory( $onappIP, $onappLogin, $onappPass );
$obj = $onapp->factory( 'VirtualMachine_BillingStatistics', true );
$obj->_virtual_machine_id = 1001;
$list       = $obj->getList();
foreach($list as $v){
    print_r($v);
}
