### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by flaviohcardoso** [virtuozzo/OnApp-PHP-Wrapper-External#49]
@MykolaVuy How can I set the IP version to be added randomly over a network interface?

In the Class **OnApp_VirtualMachine_IpAddressJoin** it would be the only one that has the version to be defined, but this is the required field **ip_address_id**

_VirtualMachine/IpAddressJoin.php_
```php
'ip_address_id'        => array(
     ONAPP_FIELD_MAP      => '_ip_address_id',
     ONAPP_FIELD_TYPE     => 'integer',
     ONAPP_FIELD_REQUIRED => true,
),
```

In the documentation the same endpoint used by this class, ip_address_id is not required.
https://docs.onapp.com/apim/6.2/ip-addresses/assign-ip-address-to-vs

I even commented on the required line and it worked perfectly.

I tried for another class **OnApp_VirtualMachine_IpAddress**, but I don't have the ip_version option there.

Let me know what is best to do or if you have any other way to add the IP and specify the version.

**Comment by MykolaVuy** [comment]
This issue with 'ip_address_id is not required' has been fixed in the last release.

Next code will set random IPv6 address:

```php
$obj = $onapp->factory('VirtualMachine_IpAddressJoin', true);
$obj->_virtual_machine_id = 3507;
$obj->_network_interface_id = 3808;
$obj->_ip_net_id = 3103;
$obj->_ip_range_id = 2820;
$obj->_ip_version = 6;

$obj->assignIPAddress();
```
